package mt

import (
	"encoding/hex"
	"strings"
	"testing"
)

// Vectors from mnemonic-transaction/crates/mt-codec/src/test_vectors/mt1_v1.json,
// generated by an independent Python implementation
// (mnemonic-engrave/scripts/gen-mt1-vectors.py) against a real node — so they
// can falsify both mt-codec and this port.

// "even": a real signed 222-byte P2WPKH tx, 6 chunks of 37 B, set 0x2dcf2.
var even = []string{
	"mt1p9h8jqq9qqqqgqqqqqqqyqherdfykhhpey6z2cvafak8804qd7g0dl6v8ex9wr2cvky023skwkeud2229sax",
	"mt1p9h8jqq9qqphgdqqqqqqqq0mllllupyqj6vqqqqqqqqzcqpfsw7ph2rt5w54kt768636cls8zxg0najlzunp",
	"mt1p9h8jqq9qqzj8yqpnzw4vl2rwffqyqqqqqkqq282yyhc2vavd20hvk94pz39hts3u5s9a0qd8pwskxfl7ju5",
	"mt1p9h8jqq9qqrqfrnq3qzyp77h37cnxzvwutegzmzy5zrrrfvrpykdfsckvk03dcq6rcjtvlsfcglv7zx43yaz",
	"mt1p9h8jqq9qqylgpzqmhcwhuupdvnrc82rncvzzdahpgjsdwgu52jd7vmxsve9x3w5ujeqyssuvddxvwqze4ve",
	"mt1p9h8jqq9qq9qdcc7h75twfxyf340c4sgqzhfdq6xtgt7zhxngpwa049l0z59l6jqcqqqqqq5k5y2ye5nv8yf",
}

const evenRawHex = "020000000001017c8da925af70e49a12b0cea7b639df5037c87b7fa61f262b86ac32c47aa3ba1a0000000000fdffffff02404b4c0000000000160014c1de0dd435d1d4ad97ed1f51d63f91c800cc4eab3ea1b92901000000160014751097c299d6354fbb2c5a84512dd708f2902f5e0247304402207debc7d89984c7717940b622504318d2c184966a618b32cf8b700d0f125b3ffa02206ef875f9c0b5931e0ea1cf0c109bdb8512835c8e51526f99b3419929a2ea7259012103718f5fd45b926226357e2b0400574b41a32d0bf0ae69a02eebea5fbc542ff52060000000"
const evenTxid = "2dcf2b973d52044b1e58c988a5a59d388073ff05598b0a1e93eeb04c72ebf630"

// "uneven": 284 B, 4 outputs, 8 chunks of 36 B with a short 32 B final chunk,
// set 0x3b426 — exercises the short-final-chunk path.
var uneven = []string{
	"mt1p8dpxqq8qqqqgqqqqqqqyqherdfykhhpey6z2cvafak8804qd7g0dl6v8ex9wr2cvky0gukj5httfg6h7u",
	"mt1p8dpxqq8qqp5wap5qqqqqqqpl0llllsgszzpuqqqqqqqqtqq9rdnsfazpda3cnggdxz0yfaj3pagq9d42j",
	"mt1p8dpxqq8qqz90aylmzacqeknyju4g5szqqqqqtqq98sgd0rn6x5tj577dkjzlzq0f5pzyckjju6fpmqh96",
	"mt1p8dpxqq8qqrf83ylqyyrcqqqqqqqqtqq9xur0xnerhulyyhqvdy24udptewpdatz47qcc0mvtxgxe3pcvn",
	"mt1p8dpxqq8qqy95qqqqqqqqtqq9rxttg3c8z9u53cphq2ddudk066c4mtkgszgucygq3qdsudzl26yqsqxcp",
	"mt1p8dpxqq8qq9ehdgpydwehxr77hcne7fycxrlx2hzpaqs8f8dz47au7e0j798ypzqur95cyr3vzslwgnlgm",
	"mt1p8dpxqq8qqx6x7jqlleq76ku4e0d98tkufltxahwluu73u2gjfq8nwu7kspyyphrr6l6srk58kpq022ayd",
	"mt1p8dpxqq8qq8twfxyf340c4sgqzhfdq6xtgt7zhxngpwa049l0z59l6jqcsqqqqqylatwa94hql0v",
}

const unevenTxid = "3b426e922a2cbf018fb6cd5650a39f60f3eb40fe85ca435cc049f6551b3462b9"

// Forged fixtures, generated by the SAME independent Python encoder so they
// are BCH-valid and reach the semantic checks:
//
// smuggled: 32 bytes of 0xAB under display-txid prefix "deadb" — reassembles,
// does not PARSE as a transaction.
const smuggled = "mt1pm6kmqqqqqq4w46h2at4w46h2at4w46h2at4w46h2at4w46h2at4w46h2at4w4sqxxtg7uwrnug7"

// foreign: the REAL even transaction encoded under chunk_set_id 0x00000 —
// reassembles, parses, and fails the txid binding.
var foreign = []string{
	"mt1pqqqqqq9qqqqgqqqqqqqyqherdfykhhpey6z2cvafak8804qd7g0dl6v8ex9wr2cvky023shuayazhuzld98",
	"mt1pqqqqqq9qqphgdqqqqqqqq0mllllupyqj6vqqqqqqqqzcqpfsw7ph2rt5w54kt768636clsxsd4wuqyhcptq",
	"mt1pqqqqqq9qqzj8yqpnzw4vl2rwffqyqqqqqkqq282yyhc2vavd20hvk94pz39hts3u5s9a0qv42n3emlhy0y4",
	"mt1pqqqqqq9qqrqfrnq3qzyp77h37cnxzvwutegzmzy5zrrrfvrpykdfsckvk03dcq6rcjtvlsg2rzd3lsate9r",
	"mt1pqqqqqq9qqylgpzqmhcwhuupdvnrc82rncvzzdahpgjsdwgu52jd7vmxsve9x3w5ujeqyssa7xs8rnk2rg5c",
	"mt1pqqqqqq9qq9qdcc7h75twfxyf340c4sgqzhfdq6xtgt7zhxngpwa049l0z59l6jqcqqqqqq4ylettyzmk6ug",
}

func TestParseHeader(t *testing.T) {
	for i, s := range even {
		h, err := ParseHeader(s)
		if err != nil {
			t.Fatalf("chunk %d: %v", i, err)
		}
		want := Header{Version: 1, ChunkSetID: 0x2dcf2, TotalChunks: 6, ChunkIndex: i}
		if h != want {
			t.Errorf("chunk %d: got %+v, want %+v", i, h, want)
		}
	}
	if _, err := ParseHeader("md1yqpqqxqq8xtwhw4xwn4qh"); err == nil {
		t.Error("ParseHeader must refuse a non-mt string")
	}
}

func TestDecodeReassemblesAndConfirms(t *testing.T) {
	for _, tc := range []struct {
		name    string
		set     []string
		rawHex  string
		txid    string
		in, out int
	}{
		{"even", even, evenRawHex, evenTxid, 1, 2},
		{"uneven", uneven, "", unevenTxid, 1, 4},
	} {
		tx, err := Decode(tc.set)
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if tx.TxidDisplay != tc.txid {
			t.Errorf("%s: txid %s, want %s", tc.name, tx.TxidDisplay, tc.txid)
		}
		if tc.rawHex != "" && hex.EncodeToString(tx.Raw) != tc.rawHex {
			t.Errorf("%s: raw bytes diverge", tc.name)
		}
		if tx.Inputs != tc.in || tx.Outputs != tc.out || !tx.SegWit {
			t.Errorf("%s: summary %+v", tc.name, tx)
		}
	}
}

func TestDecodeIsOrderIndependentAndDuplicateTolerant(t *testing.T) {
	shuffled := []string{even[4], even[0], even[5], even[2], even[1], even[3]}
	tx, err := Decode(shuffled)
	if err != nil || tx.TxidDisplay != evenTxid {
		t.Fatalf("shuffled: %v", err)
	}
	dup := append(append([]string{}, even...), even[2], strings.ToUpper(even[3]))
	tx, err = Decode(dup)
	if err != nil || tx.TxidDisplay != evenTxid {
		t.Fatalf("duplicates: %v", err)
	}
}

func TestDecodeRefusesWhatItMust(t *testing.T) {
	// A missing chunk.
	if _, err := Decode(even[:5]); err == nil {
		t.Error("an incomplete set must not decode")
	}
	// A chunk from another set.
	if _, err := Decode(append(append([]string{}, even...), uneven[0])); err == nil {
		t.Error("a mixed set must be refused")
	}
	// A damaged string: NO correction on this side, ever.
	bad := even[0][:len(even[0])-1] + "y"
	if _, err := Decode([]string{bad}); err == nil {
		t.Error("a damaged string must be refused, not corrected")
	}
	if _, err := Decode(nil); err == nil {
		t.Error("empty input must error")
	}
}

// The two arms that make confirmation SEMANTIC rather than structural.
func TestSmuggledEntropyAndForgedSetIdAreRefused(t *testing.T) {
	// 32 bytes of entropy: complete, BCH-valid, reassembles — not a tx.
	if _, err := Decode([]string{smuggled}); err == nil {
		t.Error("wrapped entropy must not confirm")
	}
	// A real transaction under a foreign chunk_set_id: parses — binding fails.
	if _, err := Decode(foreign); err == nil {
		t.Error("a foreign chunk_set_id must fail the txid binding")
	}
}

func TestParseTxMatchesTheNode(t *testing.T) {
	raw, _ := hex.DecodeString(evenRawHex)
	tx, err := ParseTx(raw)
	if err != nil {
		t.Fatal(err)
	}
	if tx.TxidDisplay != evenTxid {
		t.Errorf("txid %s, want %s", tx.TxidDisplay, evenTxid)
	}
	if tx.ChunkSetID() != 0x2dcf2 {
		t.Errorf("ChunkSetID %#x, want 0x2dcf2", tx.ChunkSetID())
	}
	// Refusals: truncations never parse and never panic; trailing bytes refuse.
	for n := range raw {
		if _, err := ParseTx(raw[:n]); err == nil {
			t.Fatalf("prefix of %d bytes accepted", n)
		}
	}
	if _, err := ParseTx(append(append([]byte{}, raw...), 0x00)); err == nil {
		t.Error("trailing bytes must refuse")
	}
	if _, err := ParseTx(make([]byte, 32)); err == nil {
		t.Error("32 zero bytes are not a transaction")
	}
}

// RED FIRST (G-P3.2). The device had NO signature check at all: parseTx called
// skipBytes for the scriptSig and DISCARDED the length. A witness-stripped
// transaction has the same txid as the honest one, so every other check --
// parse, txid derivation, chunk_set_id binding -- passes it.
//
// The host refuses this. Before this test the device would have engraved it.
func TestAStrippedTransactionIsNotSigned(t *testing.T) {
	honest := unhexT(t, "020000000001017c8da925af70e49a12b0cea7b639df5037c87b7fa61f262b86ac32c47aa3ba1a0000000000fdffffff02404b4c0000000000160014c1de0dd435d1d4ad97ed1f51d63f91c800cc4eab3ea1b92901000000160014751097c299d6354fbb2c5a84512dd708f2902f5e0247304402207debc7d89984c7717940b622504318d2c184966a618b32cf8b700d0f125b3ffa02206ef875f9c0b5931e0ea1cf0c109bdb8512835c8e51526f99b3419929a2ea7259012103718f5fd45b926226357e2b0400574b41a32d0bf0ae69a02eebea5fbc542ff52060000000")
	stripped := unhexT(t, "02000000017c8da925af70e49a12b0cea7b639df5037c87b7fa61f262b86ac32c47aa3ba1a0000000000fdffffff02404b4c0000000000160014c1de0dd435d1d4ad97ed1f51d63f91c800cc4eab3ea1b92901000000160014751097c299d6354fbb2c5a84512dd708f2902f5e60000000")

	h, err := ParseTx(honest)
	if err != nil {
		t.Fatalf("honest body must parse: %v", err)
	}
	s, err := ParseTx(stripped)
	if err != nil {
		t.Fatalf("the stripped body still parses -- that is the problem: %v", err)
	}
	if h.TxidDisplay != s.TxidDisplay {
		t.Fatal("premise broken: if the txids differed the txid alone would catch this")
	}
	if !h.EveryInputSigned {
		t.Error("the honest body's input carries a witness")
	}
	if s.EveryInputSigned {
		t.Error("the stripped body has no witness and an empty scriptSig -- unsigned")
	}
}

func unhexT(t *testing.T, s string) []byte {
	t.Helper()
	b := make([]byte, len(s)/2)
	for i := range b {
		var v byte
		for j := 0; j < 2; j++ {
			c := s[i*2+j]
			switch {
			case c >= '0' && c <= '9':
				v = v<<4 | (c - '0')
			case c >= 'a' && c <= 'f':
				v = v<<4 | (c - 'a' + 10)
			default:
				t.Fatalf("bad hex %q", c)
			}
		}
		b[i] = v
	}
	return b
}

// The predicate is PER INPUT. Mutation-tested: replacing the all() with an
// any() over the whole transaction leaves TestAStrippedTransactionIsNotSigned
// GREEN and turns this one RED. The Rust side needed exactly this second vector
// for exactly this reason -- the lesson landed twice.
func TestOneSignedInputDoesNotVouchForTheOthers(t *testing.T) {
	// Input 0 legacy-signed (non-empty scriptSig), input 1 a segwit input whose
	// witness was stripped (empty scriptSig, no witness). Serialized legacy.
	tx, err := ParseTx(unhexT(t, "020000000211111111111111111111111111111111111111111111111111111111111111110000000048473030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030ffffffff22222222222222222222222222222222222222222222222222222222222222220100000000ffffffff0150c3000000000000160014333333333333333333333333333333333333333300000000"))
	if err != nil {
		t.Fatalf("a mixed stripped body parses: %v", err)
	}
	if tx.Inputs != 2 {
		t.Fatalf("want 2 inputs, got %d", tx.Inputs)
	}
	if tx.EveryInputSigned {
		t.Error("input 1 has no scriptSig and no witness -- input 0 being signed " +
			"does not make the transaction spendable")
	}
}
