package gui

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/btcsuite/btcd/chaincfg/v2"
	"seedhammer.com/address"
	"seedhammer.com/bip380"
	"seedhammer.com/md"
)

// TestTaprootScriptPathMatchesRust is Stage 3's gate: the device derives the
// SAME receive and change addresses as the Rust primary, for taproot policies
// carrying a script tree.
//
// Before this, `address.Receive` handled key-path-only taproot and returned a
// typed errUnsupported for anything with a tree — so the device could show no
// address at all for exactly the policies this cycle exists to support, and the
// project's "derived addresses + wallet id" proof model was unreachable for
// them.
//
// The expected values are NOT written here. They come from the keyed
// conformance records generated by the Rust primary, so this is a
// cross-language check rather than a Go implementation agreeing with itself.
func TestTaprootScriptPathMatchesRust(t *testing.T) {
	paths, err := filepath.Glob(filepath.Join("..", "md", "testdata", "vectors", "keyed_tr_*.conformance.json"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(paths) == 0 {
		t.Fatal("no keyed_tr_* conformance records vendored — this gate checks NOTHING")
	}

	checked, skipped := 0, 0
	for _, p := range paths {
		name := strings.TrimSuffix(filepath.Base(p), ".conformance.json")
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(p)
			if err != nil {
				t.Fatalf("read: %v", err)
			}
			var rec struct {
				Chains map[string]struct {
					Addresses []string `json:"addresses"`
				} `json:"chains"`
			}
			if err := json.Unmarshal(raw, &rec); err != nil {
				t.Fatalf("parse: %v", err)
			}

			chunks := loadVectorChunks(t, name)
			internalIdx, isNUMS, leaves, err := md.TapLeavesChunks(chunks)
			if err != nil {
				// A key-path-only tr has no tree; that path is already covered
				// by address.Receive and is not this gate's subject.
				skipped++
				t.Skipf("%s: no script tree (%v)", name, err)
			}
			if isNUMS {
				t.Skip("NUMS internal key: no key-path spend, not this gate's subject")
			}

			_, keys, err := md.ExpandWalletPolicyChunks(chunks)
			if err != nil {
				t.Fatalf("ExpandWalletPolicy: %v", err)
			}
			byIndex := map[uint8]bip380.Key{}
			for _, k := range keys {
				children, ok := useSiteToChildren(k.UseSite)
				if !ok {
					t.Fatalf("%s: @%d has an unsupported use-site", name, k.Index)
				}
				byIndex[k.Index] = bip380.Key{
					Network:           &chaincfg.MainNetParams,
					MasterFingerprint: fpFromBytes(k.Fingerprint),
					DerivationPath:    k.OriginPath,
					Children:          children,
					KeyData:           append([]byte(nil), k.Xpub[32:65]...),
					ChainCode:         append([]byte(nil), k.Xpub[0:32]...),
				}
			}

			specs := make([]address.TapLeafSpec, 0, len(leaves))
			for _, l := range leaves {
				spec := address.TapLeafSpec{Depth: l.Depth, K: l.K}
				switch l.Kind {
				case md.TapLeafPK:
					spec.Kind = address.TapLeafPK
				case md.TapLeafMultiA:
					spec.Kind = address.TapLeafMultiA
				case md.TapLeafSortedMultiA:
					spec.Kind = address.TapLeafSortedMultiA
				}
				for _, i := range l.KeyIndices {
					spec.Keys = append(spec.Keys, byIndex[i])
				}
				specs = append(specs, spec)
			}

			for chainStr, chain := range rec.Chains {
				want := chain.Addresses
				change := chainStr == "1"
				for i, w := range want {
					got, err := address.TaprootScriptPath(
						byIndex[internalIdx], specs, uint32(i), change, &chaincfg.MainNetParams)
					if err != nil {
						t.Fatalf("%s chain %s index %d: %v", name, chainStr, i, err)
					}
					if got != w {
						t.Errorf("%s chain %s index %d:\n  go:   %s\n  rust: %s",
							name, chainStr, i, got, w)
					}
					checked++
				}
			}
		})
	}
	if checked == 0 {
		t.Fatalf("no addresses were compared (%d skipped) — the gate asserted nothing", skipped)
	}
	t.Logf("cross-checked %d taproot script-path addresses against Rust (%d vectors skipped)", checked, skipped)
}

func loadVectorChunks(t *testing.T, name string) []string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "md", "testdata", "vectors", name+".phrase.txt"))
	if err != nil {
		t.Fatalf("read %s.phrase.txt: %v", name, err)
	}
	var out []string
	for _, l := range strings.Split(string(raw), "\n") {
		l = strings.ReplaceAll(strings.TrimSpace(l), " ", "")
		if strings.HasPrefix(l, "md1") {
			out = append(out, l)
		}
	}
	return out
}
