package gui

import (
	"strings"
	"testing"
	"testing/synctest"

	"seedhammer.com/mt"
)

// ═══ P5 I-2 — A DUPLICATED CHUNK INDEX IS NAMED, NOT SWALLOWED ══════════════
//
// The scenario needs no luck. Sign the same PSBT twice -- a re-run of the
// ceremony -- and the second run differs only in witness bytes, which the txid
// ignores: SAME txid, therefore SAME chunk_set_id, same chunk count, same
// lengths. Pack strings from both runs into one payload and one index carries
// two different strings. mt.Decode refuses the set (errAmbiguousChunk) and the
// legend is substituted, but orderByIndex then keeps the LAST string per index
// and the earlier ones never reach the steel -- while the review screen showed
// the DEDUPED count and named nothing.
//
// OPERATOR RULING 2026-08-26: "last wins is fine but message to user that this
// is the rule is required so they can try again in different order. Message
// should say something like duplicate plate 13 of 20 found, last wins."
//
// So last-wins stays and the screen says so, naming EVERY colliding index.

// txEvenAlt34 is chunks 3 and 4 of the pinned `even` transaction RE-SIGNED:
// the same 222 bytes with two bytes flipped inside the witness DER signature
// (raw offsets 120 and 155, both inside the 71-byte signature push at 112), so
// the txid -- computed over the witness-STRIPPED form -- is unchanged and the
// chunk_set_id is still 0x2dcf2.
//
// Generated by the same independent Python encoder that minted every other mt1
// fixture in this tree (mnemonic-engrave/scripts/gen-mt1-vectors.py, encode()),
// which reproduces txEven byte for byte from the same input -- so these are
// BCH-valid strings a real second ceremony could hand the operator, not
// hand-edited text that would fail the checksum before reaching the defect.
var txEvenAlt34 = []string{
	3: "mt1p9h8jqq9qqrqfrnq3qzyp77h3e8nxzvwutegzmzy5zrrrfvrpykdfsckvk03dcq6rcjtvlsa24c0zv295mkw",
	4: "mt1p9h8jqq9qqylgpzqmhcwhunldvnrc82rncvzzdahpgjsdwgu52jd7vmxsve9x3w5ujeqysslrkqvr6zed57r",
}

// txEvenTwoRuns is the payload an operator who packed both ceremonies has:
// run 1 whole, then the two strings run 2 disagrees on. Interleaving is what
// makes the engraved subset order-dependent, which is the finding.
func txEvenTwoRuns() []string {
	return []string{
		txEven[0], txEven[1], txEven[2],
		txEven[3], txEvenAlt34[3],
		txEven[4], txEvenAlt34[4],
		txEven[5],
	}
}

// THE FIXTURE IS THE FINDING, so it is asserted rather than assumed: these
// strings really do collide, the set really does not decode, and the losing
// half really would confirm on its own. A fixture that quietly stopped
// colliding would turn every test below into a false PASS.
func TestTheTwoRunFixtureCollidesTheWayTheFindingSays(t *testing.T) {
	for i, s := range txEvenAlt34 {
		if s == "" {
			continue
		}
		h, err := mt.ParseHeader(s)
		if err != nil {
			t.Fatalf("alt chunk %d is not a valid mt1 string: %v", i, err)
		}
		orig, err := mt.ParseHeader(txEven[i])
		if err != nil {
			t.Fatal(err)
		}
		if h != orig {
			t.Fatalf("alt chunk %d header %+v != %+v -- it is not the same slot", i, h, orig)
		}
		if strings.EqualFold(s, txEven[i]) {
			t.Fatalf("alt chunk %d is the same string; nothing collides", i)
		}
	}
	if _, err := mt.Decode(txEvenTwoRuns()); err == nil {
		t.Fatal("a set holding two different strings for one index must not decode")
	}
	// THE ESCALATION, asserted rather than believed. Run 1 alone is a
	// complete, coherent set that CONFIRMS -- so the strings last-wins drops
	// were worth cutting, which is what makes naming them worth a screen.
	if tx, err := mt.Decode(txEven); err != nil || tx.TxidDisplay != txEvenTxid {
		t.Fatalf("run 1 alone must confirm: %v", err)
	}
	// And so does the SPLICE: what last-wins actually engraves -- chunks 0, 1,
	// 2 and 5 from run 1, 3 and 4 from run 2 -- decodes, parses, binds to the
	// operator's own txid and reports every input signed, because the txid is
	// defined to ignore exactly the bytes the two runs disagree about. The
	// plate's permanent legend would say DOES NOT DECODE while the set on it
	// decodes to a transaction nobody signed. That is why the drop cannot stay
	// silent, and it is pinned here so the scenario cannot quietly stop being
	// reachable.
	spliced := orderByIndex(txEvenTwoRuns())
	tx, err := mt.Decode(spliced)
	if err != nil {
		t.Fatalf("the engraved splice no longer decodes (%v) -- re-read this test "+
			"before relaxing it; the finding depends on it decoding", err)
	}
	if tx.TxidDisplay != txEvenTxid || !tx.EveryInputSigned {
		t.Fatalf("splice: txid %q signed=%v", tx.TxidDisplay, tx.EveryInputSigned)
	}
}

// LAST WINS IS THE RULING, so it is pinned: this test fails if a later change
// "fixes" the dedup instead of reporting it.
func TestLastWinsIsStillTheRule(t *testing.T) {
	got := orderByIndex(txEvenTwoRuns())
	if len(got) != 6 {
		t.Fatalf("got %d strings, want 6 -- one per index", len(got))
	}
	if got[3] != txEvenAlt34[3] || got[4] != txEvenAlt34[4] {
		t.Error("the LAST string for an index must be the one kept")
	}
	// ...and reversing the payload order reverses which copy is cut, which is
	// exactly what the message tells the operator they can do.
	rev := []string{txEven[0], txEven[1], txEven[2],
		txEvenAlt34[3], txEven[3], txEvenAlt34[4], txEven[4], txEven[5]}
	got = orderByIndex(rev)
	if got[3] != txEven[3] || got[4] != txEven[4] {
		t.Error("re-ordering the payload must change which copy survives")
	}
}

// EVERY collision is named, not just the first, and the numbers are the ones
// the operator can act on: 1-BASED (the header's index is 0-based and no
// screen in this program shows it that way) against the set's DECLARED count.
func TestDuplicateChunkIndicesNamesEveryCollisionOneBased(t *testing.T) {
	idx, total := duplicateChunkIndices(txEvenTwoRuns())
	if total != 6 {
		t.Errorf("declared count %d, want 6 (the header's, not the deduped length)", total)
	}
	if len(idx) != 2 || idx[0] != 3 || idx[1] != 4 {
		t.Fatalf("got %v, want both colliding indices [3 4]", idx)
	}
	if got := namedChunks(idx, total); got != "strings 4 and 5 of 6" {
		t.Errorf("named %q; the operator counts plates from one, not from zero", got)
	}
	if got := namedChunks(idx[:1], total); got != "string 4 of 6" {
		t.Errorf("one collision reads %q", got)
	}
	if got := namedChunks([]int{0, 3, 4}, 6); got != "strings 1, 4 and 5 of 6" {
		t.Errorf("three collisions read %q", got)
	}
}

// THE TOTAL IS THE DECLARED COUNT, and this test exists because the first
// version of it could not tell that apart: on a COMPLETE two-run set the
// declared count, the number of distinct indices and the deduped length are
// all 6, so an implementation that reported any of the three passed. Mutating
// `total` to the deduped length survived.
//
// So the fixture is a set that is BOTH short and duplicated -- the operator
// packed part of run 1 and part of run 2, which is the likelier accident of
// the two. Declared 6, four indices present, four strings after the dedup: the
// message must say "of 6" or it names a set that does not exist and the
// operator cannot tell which strings they are still missing.
func TestTheTotalIsTheDeclaredCountNotTheDedupedLength(t *testing.T) {
	short := []string{txEven[0], txEven[1], txEven[2], txEven[3], txEvenAlt34[3]}
	idx, total := duplicateChunkIndices(short)
	if len(idx) != 1 || idx[0] != 3 {
		t.Fatalf("got %v, want [3]", idx)
	}
	if total != 6 {
		t.Errorf("total %d: the header declares 6; 4 is the deduped length and "+
			"5 is how many strings were packed", total)
	}
	if got := namedChunks(idx, total); got != "string 4 of 6" {
		t.Errorf("named %q", got)
	}
	ctx := NewContext(newPlatform())
	ctx.sysw = sessionWith(short...)
	cands, _ := payloadTransactions(ctx)
	if len(cands) != 1 {
		t.Fatalf("got %d candidates", len(cands))
	}
	joined := strings.Join(transactionReviewLines(cands[0]), "\n")
	if !strings.Contains(joined, "Duplicate string 4 of 6 found, last wins.") {
		t.Errorf("the screen must count against the DECLARED total:\n%s", joined)
	}
	// ...and this set is short as well as duplicated, so the legend is still
	// the missing-strings one. Naming the duplicate must not have displaced it.
	if !strings.Contains(joined, legendSubstitution(false)) {
		t.Errorf("the missing-strings legend is gone:\n%s", joined)
	}
}

// An EXACT duplicate is not a collision. mt.Decode calls it "a well-kept
// drawer, not an error" and tolerates it, and a codex32 string is
// consistent-case, so an all-uppercase copy carries the identical payload.
// Warning about either would send the operator off to re-pack a payload that
// lost nothing.
func TestAnIdenticalDuplicateIsNotReported(t *testing.T) {
	same := append(append([]string{}, txEven...), txEven[2], strings.ToUpper(txEven[3]))
	if _, err := mt.Decode(same); err != nil {
		t.Fatalf("mt.Decode tolerates these; the message must too: %v", err)
	}
	if idx, _ := duplicateChunkIndices(same); len(idx) != 0 {
		t.Errorf("reported %v for a set that lost nothing", idx)
	}
}

// THE PAYLOAD PATH, end to end into the words the operator reads.
func TestTheReviewScreenNamesEveryDuplicatedString(t *testing.T) {
	ctx := NewContext(newPlatform())
	ctx.sysw = sessionWith(txEvenTwoRuns()...)
	cands, _ := payloadTransactions(ctx)
	if len(cands) != 1 {
		t.Fatalf("got %d candidates", len(cands))
	}
	joined := strings.Join(transactionReviewLines(cands[0]), "\n")
	if !strings.Contains(joined, "Duplicate strings 4 and 5 of 6 found, last wins.") {
		t.Errorf("the screen never names the dropped strings:\n%s", joined)
	}
	// BEARER MATERIAL. An mt1 string is a chunk of a signed transaction;
	// naming which index collided is the message, printing the string is a
	// leak onto a screen and into a journey capture.
	for _, s := range txEvenTwoRuns() {
		if strings.Contains(joined, s[:24]) {
			t.Errorf("the screen renders an mt1 string body:\n%s", joined)
		}
	}
}

// THE NFC PATH. txGather.offer is the finding's second consumer of
// orderByIndex, and it thins the same way -- a set scanned from two ceremonies
// reaches the identical review screen.
func TestTheGatherNamesDuplicatesToo(t *testing.T) {
	g := newTxGather()
	var c txCandidate
	var done bool
	for _, s := range txEvenTwoRuns() {
		c, done = g.offer(s)
	}
	if !done {
		t.Fatalf("the set never became decidable: %q", g.msg)
	}
	if c.confirmed {
		t.Fatal("a set with two payloads for one index must not confirm")
	}
	joined := strings.Join(transactionReviewLines(c), "\n")
	if !strings.Contains(joined, "Duplicate strings 4 and 5 of 6 found, last wins.") {
		t.Errorf("the scanned set's review screen names nothing:\n%s", joined)
	}
}

// THE WALK: the message has to be on the screen the operator actually
// confirms from, not merely in a slice some test joins. `until` does not page,
// so the headline is asserted where Continue is pressed; the sentence itself
// is then reached the way a reader reaches it.
func TestWalkADuplicatedStringIsNamedBeforeTheCut(t *testing.T) {
	synctest.Test(t, func(t *testing.T) {
		w := newTxWalk(t, txEvenTwoRuns()...)
		defer w.quit()

		got := w.until("UNCONFIRMED SET")
		if !uiContains(got, "DUPLICATE STRINGS") {
			t.Errorf("the operator can press Continue from this page without "+
				"ever learning a string was dropped:\n%q", got)
		}
		got = w.paged("Duplicate strings 4 and 5 of 6 found, last wins.")
		if !uiContains(got, "Duplicatestrings4and5of6found,lastwins.") {
			t.Errorf("the sentence must be whole: %q", got)
		}
		w.paged("different order")
	})
}

// RULED 2026-08-26 (operator): "just say incomplete/does not decode".
//
// The unconfirmed screen hardcoded "but the set is not complete." while its own
// legend three lines below distinguishes two cases: INCOMPLETE - DOES NOT
// DECODE (every index present, still will not reassemble — the two-run splice)
// and INCOMPLETE - MISSING STRINGS. For a two-run payload every index IS
// present, so the screen asserted something false while the legend beside it
// was right. Only one of them could be true, and the operator reads both.
//
// The screen must now cover both cases without asserting which.
func TestTheUnconfirmedScreenDoesNotContradictItsOwnLegend(t *testing.T) {
	for _, complete := range []bool{true, false} {
		c := txCandidate{
			confirmed: false,
			csid:      0x2dcf2,
			strs:      []string{"mt1one", "mt1two"},
			subst:     legendSubstitution(complete),
		}
		var joined string
		for _, l := range transactionReviewLines(c) {
			joined += l + "\n"
		}
		if strings.Contains(joined, "but the set is not complete.") {
			t.Fatalf("complete=%v: the screen still asserts incompleteness "+
				"unconditionally, which is false for a set whose indices are "+
				"all present:\n%s", complete, joined)
		}
		if !strings.Contains(joined, "incomplete or") && !strings.Contains(joined, "does not decode") {
			t.Fatalf("complete=%v: the screen must name BOTH possibilities so it "+
				"cannot contradict the legend:\n%s", complete, joined)
		}
	}
}
