package gui

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"seedhammer.com/gui/assets"
	"seedhammer.com/seal"
)

// §10.1 — the unlockPayload menu entry is CONDITIONAL: present when the payload
// region holds a blob, invisible when it does not.
//
// unlockProgramTitles is the pager in order WITH a payload present: the NINE
// unconditional programs, then the conditional tenth. Without a payload the
// carousel must stop at "BIP-85" and never reach the last entry.
var unlockProgramTitles = []string{
	"Backup Wallet",
	"BIP-39 Password",
	"Engrave Text",
	"Account Xpub",
	"Engrave Bundle",
	"Engrave Single-Sig",
	"Engrave Multisig",
	"Wallet Policy",
	"Load Payload",
	"BIP-85",
	"Sealed Payload",
}

// sealTestVector is the subset of a SPEC §11.4 vector these tests read. The
// expected side of every hash assertion comes from THIS file rather than from a
// digest retyped into a Go test: seal/testdata/vectors.json is generated by the
// normative Rust implementation and never hand-edited, and retyped constants
// are how a port silently forks.
type sealTestVector struct {
	Name string `json:"name"`
	// Passphrase and Iterations are what let a gui test unlock a vector rather
	// than retype "beef beef ..." into a Go source file, which
	// seal/testdata/README.md:19-24 forbids.
	Passphrase      *string  `json:"passphrase"`
	Iterations      uint32   `json:"iterations"`
	Public          []string `json:"public"`
	Secret          []string `json:"secret"`
	PubLen          uint32   `json:"pub_len"`
	CtLen           uint32   `json:"ct_len"`
	BlobHex         string   `json:"blob_hex"`
	BlobSHA256      string   `json:"blob_sha256"`
	SaltHex         string   `json:"salt_hex"`
	IVHex           string   `json:"iv_hex"`
	PubhashSealed   *string  `json:"pubhash_sealed"`
	PubhashUnsealed *string  `json:"pubhash_unsealed"`
}

// sealVectorNames pins the file's shape, exactly as seal.loadVectors does. gui
// is a SECOND decoder of the same normative file, and it pinned none of what
// seal pins -- so a truncated or reordered vectors.json silently shrank the gui
// suite while seal failed loudly. (B2a-ii completeness critic, C2.)
var sealVectorNames = []string{"A", "B", "C", "D", "E", "F", "G"}

// sealVectors loads every vector and re-asserts seal's three integrity pins:
// the count, the names in order, and blob_sha256 against blob_hex.
func sealVectors(t *testing.T) []sealTestVector {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("..", "seal", "testdata", "vectors.json"))
	if err != nil {
		t.Fatalf("read seal vectors: %v", err)
	}
	var f struct {
		Vectors []sealTestVector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse seal vectors: %v", err)
	}
	if len(f.Vectors) != len(sealVectorNames) {
		t.Fatalf("vectors.json has %d vectors, want %d", len(f.Vectors), len(sealVectorNames))
	}
	for i, want := range sealVectorNames {
		if f.Vectors[i].Name != want {
			t.Fatalf("vector %d is %q, want %q", i, f.Vectors[i].Name, want)
		}
	}
	for _, v := range f.Vectors {
		sum := sha256.Sum256(mustHexBytes(t, v.BlobHex))
		if got := hex.EncodeToString(sum[:]); got != v.BlobSHA256 {
			t.Fatalf("vector %s: blob_hex hashes to %s, blob_sha256 says %s",
				v.Name, got, v.BlobSHA256)
		}
	}
	return f.Vectors
}

func mustHexBytes(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

func sealVector(t *testing.T, name string) sealTestVector {
	t.Helper()
	for _, v := range sealVectors(t) {
		if v.Name == name {
			return v
		}
	}
	t.Fatalf("no vector named %q in seal/testdata/vectors.json", name)
	return sealTestVector{}
}

// blob returns the vector's raw payload-region bytes.
func (v sealTestVector) blob(t *testing.T) []byte {
	t.Helper()
	b, err := hex.DecodeString(v.BlobHex)
	if err != nil {
		t.Fatalf("vector %s: blob_hex: %v", v.Name, err)
	}
	return b
}

func sealVectorBlob(t *testing.T, name string) []byte {
	t.Helper()
	return sealVector(t, name).blob(t)
}

// payloadReaderFor writes a vector's blob to a temp file and hands back a
// seal.Reader over it. seal.FileReader is the host stand-in for the XIP read
// (seal/read_host.go) — which is exactly the seam Platform.PayloadReader exists
// to keep out of gui: no build-tagged type is named here.
func payloadReaderFor(t *testing.T, name string) seal.Reader {
	t.Helper()
	return payloadReaderFrom(t, sealVectorBlob(t, name))
}

// payloadReaderFrom is payloadReaderFor over raw region bytes, for the tests
// that mangle or hand-build a blob. F-79 moved the flow's parameter from
// []byte to seal.Reader, so those blobs need a reader too.
func payloadReaderFrom(t *testing.T, blob []byte) seal.Reader {
	t.Helper()
	path := filepath.Join(t.TempDir(), "payload.bin")
	if err := os.WriteFile(path, blob, 0o600); err != nil {
		t.Fatalf("write payload: %v", err)
	}
	return seal.FileReader{Path: path}
}

// pagerDots measures how many dots layoutMainPager actually drew, by inverting
// its own geometry against the dot asset's size.
//
// The count is asserted against LITERAL 8 and 9 by the callers, never against
// int(bip85Derive)+1: an assertion whose expected side is derived from the same
// constant the code uses pins nothing.
func pagerDots(t *testing.T, ctx *Context, lastNav program) int {
	t.Helper()
	_, sz := layoutMainPager(&ctx.B, &descriptorTheme, backupWallet, lastNav)
	const space = 4
	dot := assets.CircleFilled.Bounds().Size().X
	n := (sz.X + space) / (dot + space)
	if (dot+space)*n-space != sz.X {
		t.Fatalf("pager is %dpx wide, which is not a whole number of %dpx dots", sz.X, dot)
	}
	return n
}

// TestUnlockPayloadInvisibleWithoutAPayload — §10.1's negative path. The
// carousel must be an EIGHT-program lap, and the ninth entry must not appear on
// any frame of it.
func TestUnlockPayloadInvisibleWithoutAPayload(t *testing.T) {
	p := newPlatform()
	p.display = sh2DisplaySize
	ctx := NewContext(p)
	if p.PayloadReader() != nil {
		t.Fatal("the default test platform must have no payload reader")
	}
	frame, drawer, quit := runUITouch(ctx, func() { uiFlow(ctx, "test") })
	defer quit()

	content, ok := frame()
	if !ok {
		t.Fatal("uiFlow produced no frame")
	}
	if !uiContains(content, unlockProgramTitles[0]) {
		t.Fatalf("initial program is not %q; got %q", unlockProgramTitles[0], content)
	}
	if uiContains(content, "Sealed Payload") {
		t.Fatalf("the Sealed Payload entry is visible with no payload present: %q", content)
	}
	_, right := arrowPoints(ctx)
	// A full lap of the UNCONDITIONAL programs: with no payload the last tap
	// must wrap back to the first program rather than step onto the conditional
	// Sealed Payload entry.
	const lap = 10
	for i := 1; i <= lap; i++ {
		want := unlockProgramTitles[i%lap]
		tap(&ctx.Router, drawer(), right)
		content, ok = frame()
		if !ok {
			t.Fatalf("no frame after tap #%d", i)
		}
		if !uiContains(content, want) {
			t.Fatalf("tap #%d: expected program %q, got %q", i, want, content)
		}
		if uiContains(content, "Sealed Payload") {
			t.Fatalf("tap #%d reached the Sealed Payload entry with no payload present: %q", i, content)
		}
	}
	if got := pagerDots(t, ctx, bip85Derive); got != 10 {
		t.Errorf("the no-payload pager draws %d dots, want 10", got)
	}
}

// TestUnlockPayloadVisibleWithAPayload — §10.1's positive path. The lap is NINE
// programs, the ninth is the new entry, and the other eight are all still
// reachable in order (the regression the const-to-runtime bound can cause).
func TestUnlockPayloadVisibleWithAPayload(t *testing.T) {
	p := newPlatform()
	p.display = sh2DisplaySize
	p.payload = payloadReaderFor(t, "E")
	ctx := NewContext(p)
	frame, drawer, quit := runUITouch(ctx, func() { uiFlow(ctx, "test") })
	defer quit()

	content, ok := frame()
	if !ok {
		t.Fatal("uiFlow produced no frame")
	}
	if !uiContains(content, unlockProgramTitles[0]) {
		t.Fatalf("initial program is not %q; got %q", unlockProgramTitles[0], content)
	}
	_, right := arrowPoints(ctx)
	const lap = 11 // 10 unconditional programs + the conditional Sealed Payload
	seenUnlock := false
	for i := 1; i <= lap; i++ {
		want := unlockProgramTitles[i%lap]
		tap(&ctx.Router, drawer(), right)
		content, ok = frame()
		if !ok {
			t.Fatalf("no frame after tap #%d", i)
		}
		if !uiContains(content, want) {
			t.Fatalf("tap #%d: expected program %q, got %q", i, want, content)
		}
		if i == lap-1 {
			if !uiContains(content, "Sealed Payload") {
				t.Fatalf("the tenth program is not Sealed Payload; got %q", content)
			}
			seenUnlock = true
		}
	}
	if !seenUnlock {
		t.Fatal("the Sealed Payload entry was never reached")
	}
	if got := pagerDots(t, ctx, unlockPayload); got != 11 {
		t.Errorf("the payload-present pager draws %d dots, want 10", got)
	}
}

// TestUnlockPayloadEntrySelectable presses OK on the new entry and drives it
// into the flow. Navigability only proves the entry is in the carousel; without
// this the feature ships with a dead menu item and a fully green suite, which
// is the exact failure gui/text_program_test.go's own selectable test exists to
// prevent.
//
// It is also the ONLY test that proves the bytes uiFlow PROBED are the bytes
// the flow receives: the digest on screen is computed from them.
func TestUnlockPayloadEntrySelectable(t *testing.T) {
	p := newPlatform()
	p.display = sh2DisplaySize
	p.payload = payloadReaderFor(t, "E")
	ctx := NewContext(p)
	frame, drawer, quit := runUITouch(ctx, func() { uiFlow(ctx, "test") })
	defer quit()
	if _, ok := frame(); !ok {
		t.Fatal("uiFlow produced no frame")
	}
	_, right := arrowPoints(ctx)
	for i := 0; i < 10; i++ {
		tap(&ctx.Router, drawer(), right)
		if _, ok := frame(); !ok {
			t.Fatalf("no frame after tap #%d", i+1)
		}
	}
	tapNavSlot(t, ctx, drawer(), Button3)
	content, ok := pumpUntil(frame, "Public data hash", 32)
	if !ok {
		t.Fatalf("selecting the Sealed Payload entry did not open the flow; got %q", content)
	}
	want := sealVector(t, "E").PubhashUnsealed
	if !uiContains(content, *want) {
		t.Errorf("the flow did not receive the probed payload: no digest %s in %q", *want, content)
	}
}

// TestUnlockPayloadWrapsBothDirections. The prev wrap and the next wrap are
// SEPARATE sites and a fix to one does not fix the other, so both are driven in
// both states. The next wrap is covered by the lap tests above; this pins prev.
func TestUnlockPayloadWrapsBothDirections(t *testing.T) {
	for _, tc := range []struct {
		name     string
		vector   string
		wantLast string
	}{
		{"no payload", "", "BIP-85"},
		{"payload present", "E", "Sealed Payload"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := newPlatform()
			p.display = sh2DisplaySize
			if tc.vector != "" {
				p.payload = payloadReaderFor(t, tc.vector)
			}
			ctx := NewContext(p)
			frame, drawer, quit := runUITouch(ctx, func() { uiFlow(ctx, "test") })
			defer quit()
			if _, ok := frame(); !ok {
				t.Fatal("uiFlow produced no frame")
			}
			left, _ := arrowPoints(ctx)
			tap(&ctx.Router, drawer(), left)
			content, ok := frame()
			if !ok {
				t.Fatal("no frame after the left tap")
			}
			if !uiContains(content, tc.wantLast) {
				t.Fatalf("Left from the first program did not wrap to %q; got %q", tc.wantLast, content)
			}
			// And the wrap target is the LAST program: one more Left must not
			// land on it again.
			tap(&ctx.Router, drawer(), left)
			content, ok = frame()
			if !ok {
				t.Fatal("no frame after the second left tap")
			}
			if uiContains(content, tc.wantLast) {
				t.Fatalf("two Lefts stayed on %q; the wrap bound is off by one: %q", tc.wantLast, content)
			}
		})
	}
}

// countingReader instruments a seal.Reader so a test can tell a PROBE from a
// READ. F-79's whole claim is about which of the two startup performs, and
// nothing else in the harness can observe that.
type countingReader struct {
	inner  seal.Reader
	reads  *int
	probes *int
}

func (r *countingReader) Probe() bool {
	*r.probes++
	return r.inner.Probe()
}

func (r *countingReader) Read() ([]byte, error) {
	*r.reads++
	return r.inner.Read()
}

// F-79. The startup probe must not read the region: a 64 KB allocation held for
// the GUI's lifetime is ~14% of free heap, and the menu only needs to know
// whether MNEMBLOB is there.
func TestStartupProbesWithoutReadingTheRegion(t *testing.T) {
	var reads, probes int
	r := &countingReader{inner: payloadReaderFor(t, "D"), reads: &reads, probes: &probes}
	p := newPlatform()
	p.display = sh2DisplaySize
	p.payload = r
	ctx := NewContext(p)
	frame, drawer, quit := runUITouch(ctx, func() { uiFlow(ctx, "test") })
	defer quit()
	if _, ok := frame(); !ok {
		t.Fatal("uiFlow produced no frame")
	}
	// The carousel opens on "Backup Wallet" and pumping frames sends no input,
	// so the LAST entry is reached the way every sibling test in this file
	// reaches it: one right tap per program ahead of it. Measured -- a bare pump
	// never leaves the first program, so the guard below can only succeed after
	// navigating.
	_, right := arrowPoints(ctx)
	var content string
	for i := 0; i < 10; i++ {
		tap(&ctx.Router, drawer(), right)
		c, ok := frame()
		if !ok {
			t.Fatalf("no frame after tap #%d", i+1)
		}
		content = c
	}
	if !uiContains(content, "Sealed Payload") {
		t.Fatalf("the menu entry never appeared, so the probe did not report present; got %q", content)
	}
	if probes == 0 {
		t.Fatal("startup never probed")
	}
	if reads != 0 {
		t.Fatalf("startup called Read %d times; F-79 requires the region NOT be read "+
			"until the flow is entered", reads)
	}
}
