package codex32

import (
	"crypto/sha256"
	"strings"
	"testing"
)

// Vectors from mnemonic-transaction/crates/mt-codec/src/test_vectors/mt1_v1.json
// (the "even" vector: a real signed 222-byte transaction, chunk_set_id
// 0x2dcf2). Strings verbatim; that corpus was generated by an independent
// Python implementation, so it can falsify this port.
var mtEven = []string{
	"mt1p9h8jqq9qqqqgqqqqqqqyqherdfykhhpey6z2cvafak8804qd7g0dl6v8ex9wr2cvky023skwkeud2229sax",
	"mt1p9h8jqq9qqphgdqqqqqqqq0mllllupyqj6vqqqqqqqqzcqpfsw7ph2rt5w54kt768636cls8zxg0najlzunp",
	"mt1p9h8jqq9qqzj8yqpnzw4vl2rwffqyqqqqqkqq282yyhc2vavd20hvk94pz39hts3u5s9a0qd8pwskxfl7ju5",
	"mt1p9h8jqq9qqrqfrnq3qzyp77h37cnxzvwutegzmzy5zrrrfvrpykdfsckvk03dcq6rcjtvlsfcglv7zx43yaz",
	"mt1p9h8jqq9qqylgpzqmhcwhuupdvnrc82rncvzzdahpgjsdwgu52jd7vmxsve9x3w5ujeqyssuvddxvwqze4ve",
	"mt1p9h8jqq9qq9qdcc7h75twfxyf340c4sgqzhfdq6xtgt7zhxngpwa049l0z59l6jqcqqqqqq5k5y2ye5nv8yf",
}

func TestValidMTAcceptsThePinnedVector(t *testing.T) {
	for _, s := range mtEven {
		if !ValidMT(s) {
			t.Errorf("ValidMT(%q) = false", s)
		}
		if !ValidMT(strings.ToUpper(s)) {
			t.Errorf("consistently uppercase must validate: %q", s)
		}
	}
}

func TestValidMTRejectsDamageMixedCaseAndSiblings(t *testing.T) {
	s := mtEven[0]
	// One flipped character: NO correction, pure verify.
	flipped := s[:len(s)-1] + "y"
	if flipped == s {
		flipped = s[:len(s)-1] + "x"
	}
	if ValidMT(flipped) {
		t.Error("a damaged string must not validate (no correction here)")
	}
	// Mixed case.
	if ValidMT("M" + s[1:]) {
		t.Error("mixed case must be refused")
	}
	// A valid md1 is not an mt1 — the target residues differ.
	md1 := "md1fv9wjpqpqpm6jzzqqvqpdqnf4ztqq4gy99tzyzyzdv7xh9vpdwu3t7dhhesk2tl3"
	if !ValidMD(md1) {
		t.Fatal("premise: the md1 fixture is valid")
	}
	if ValidMT(md1) {
		t.Error("an md1 string must not validate as mt1")
	}
	if ValidMD(mtEven[0]) || ValidMK(mtEven[0]) {
		t.Error("an mt1 string must not validate as md1/mk1")
	}
	// Too short / too long.
	if ValidMT("mt1qqq") {
		t.Error("shorter than header+checksum must be refused")
	}
}

// The constant is DERIVED, not pasted: top 65 bits of
// SHA-256("shibbolethnumstransaction"). A constant copied from a sibling
// would checksum consistently with itself and be unreadable by every other
// implementation — the exact defect class mt-codec's own consts tests guard.
func TestMTTargetReproducesFromDomain(t *testing.T) {
	d := sha256.Sum256([]byte("shibbolethnumstransaction"))
	var hi, lo uint64
	for _, b := range d[:8] {
		hi = hi<<8 | uint64(b)
	}
	for _, b := range d[8:16] {
		lo = lo<<8 | uint64(b)
	}
	// top 65 bits of the 128-bit big-endian value = value >> 63.
	wantHi := hi >> 63
	wantLo := hi<<1 | lo>>63
	if wantHi != mtRegularTargetHi || wantLo != mtRegularTargetLo {
		t.Errorf("mt target drift: got hi=%#x lo=%#x, derived hi=%#x lo=%#x",
			mtRegularTargetHi, mtRegularTargetLo, wantHi, wantLo)
	}
	// ...and it is no sibling's.
	if mtRegularTargetHi == mkRegularTargetHi && mtRegularTargetLo == mkRegularTargetLo {
		t.Error("mt1 is using mk1's target")
	}
	if mtRegularTargetHi == mdRegularTargetHi && mtRegularTargetLo == mdRegularTargetLo {
		t.Error("mt1 is using md1's target")
	}
}

func TestMTDataSymbolsStripsTheChecksum(t *testing.T) {
	syms, err := MTDataSymbols(mtEven[0])
	if err != nil {
		t.Fatal(err)
	}
	// 87 chars = "mt1" + 84-symbol data part; minus 13 checksum = 71 symbols
	// (11 header + 60 payload symbols for a 37-byte chunk), header first.
	if len(syms) != 71 {
		t.Fatalf("got %d symbols, want 71", len(syms))
	}
	// First symbol is the wire version, 1.
	if syms[0] != 1 {
		t.Errorf("version symbol = %d, want 1", syms[0])
	}
	if _, err := MTDataSymbols("md1yqpqqxqq8xtwhw4xwn4qh"); err == nil {
		t.Error("MTDataSymbols must refuse a non-mt string")
	}
}
