#!/usr/bin/env bash
# Vendor the Rust primary's keyed + compose corpus (every MANIFEST vector named
# keyed_* or compose_*, except the separately pinned compose_refusal_*) into
# md/testdata/vectors/ and write the provenance
# pin md/compose_vectors_pin_test.go checks. Re-run on every re-pin.
#
#   scripts/vendor-compose-vectors.sh [/path/to/descriptor-mnemonic]
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-$HERE/../descriptor-mnemonic}"
VEC="$SRC/crates/md-codec/tests/vectors"
DST="$HERE/md/testdata/vectors"
PIN="$HERE/md/testdata/compose_vectors.provenance.json"
[ -d "$VEC" ] || { echo "no vectors at $VEC" >&2; exit 2; }
commit=$(git -C "$SRC" rev-parse HEAD)
clean=true; [ -z "$(git -C "$SRC" status --porcelain -- crates/md-codec/tests/vectors)" ] || clean=false
# THE WHOLE KEYED TIER, minus the refusal vectors (F-630 D4). The selector used
# to be '^(keyed_)?compose_', which reaches 32 of the 41 records the md-codec
# 0.44.0 xpub-header rewrite moved and leaves 9 stale -- and a gate over a
# corpus that is still stale in 9 places is a RED gate, which is worse than no
# gate. The other 14 keyed vectors had no provenance pin at all.
#
# compose_refusal_* is EXCLUDED because it is pinned separately, by
# md/testdata/compose_refusal_vectors.provenance.json. Without the exclusion
# this selects 177 files against a pin of 176 and trips
# md/compose_vectors_pin_test.go.
mapfile -t files < <(cd "$VEC" && ls | grep -E '^(keyed_|compose_)' | grep -vE '^compose_refusal_' | sort)
[ "${#files[@]}" -gt 0 ] || { echo "no compose_* vectors in $VEC" >&2; exit 2; }
for f in "${files[@]}"; do cp "$VEC/$f" "$DST/$f"; done
python3 - "$PIN" "$commit" "$clean" "$DST" "${files[@]}" <<'PY'
import hashlib, json, sys, os, datetime
pin, commit, clean, dst, files = sys.argv[1], sys.argv[2], sys.argv[3] == "true", sys.argv[4], sys.argv[5:]
rows = [{"name": f, "sha256": hashlib.sha256(open(os.path.join(dst, f), "rb").read()).hexdigest()} for f in files]
names = sorted({f.split(".", 1)[0] for f in files})
doc = {
  "_comment": [
    "PROVENANCE PIN for the vendored compose corpus (wallet-policy composer, Stage 2).",
    "Generated by scripts/vendor-compose-vectors.sh; never edited by hand.",
    "md/compose_vectors_pin_test.go fails if any pinned file's sha256 disagrees,",
    "if the file count is not the one recorded below, or if the vector names",
    "drift from its list.",
    "",
    "THE COUNT IS NOT REPEATED HERE. It said 156 while the gate asserted 161,",
    "and stayed wrong through a re-vendor to 176 -- then a review read 156 out",
    "of this comment, reported it, and a commit message repeated it. Three",
    "readers, one stale literal, and nothing in between could tell. A number",
    "that must agree with another number belongs in ONE of the two places.",
    "TO RE-PIN: scripts/vendor-compose-vectors.sh /path/to/descriptor-mnemonic",
  ],
  "repo": "descriptor-mnemonic",
  "remote": "git@github.com:bg002h/descriptor-mnemonic.git",
  "commit": commit,
  "repo_clean_when_recorded": clean,
  "path": "crates/md-codec/tests/vectors",
  "files": rows,
  "file_count": len(rows),
  "vectors": len(names),
  "recorded_at": datetime.date.today().isoformat(),
}
json.dump(doc, open(pin, "w"), indent=2); open(pin, "a").write("\n")
print("vendored %d files, %d vectors, primary %s" % (len(rows), len(names), commit[:12]))
PY
