#!/usr/bin/env bash
# Vendor the Rust primary's Liana recipe evidence (SPEC_liana_unspendable
# _internal_key §8.1) into md/testdata/liana_cases.json and write the provenance
# pin md/liana_test.go checks. Re-run on every re-pin.
#
#   scripts/vendor-liana-cases.sh [/path/to/descriptor-mnemonic]
#
# The primary copy is itself vendored from mnemonic-engrave's harness evidence by
# descriptor-mnemonic's scripts/vendor-liana-evidence.sh; this repo takes the
# PRIMARY's copy, never the evidence directly (Rust-primary rule).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-$HERE/../descriptor-mnemonic}"
REL="crates/md-codec/tests/fixtures/liana/cases.json"
DST="$HERE/md/testdata/liana_cases.json"
PIN="$HERE/md/testdata/liana_cases.provenance.json"
[ -f "$SRC/$REL" ] || { echo "no cases at $SRC/$REL" >&2; exit 2; }
commit=$(git -C "$SRC" rev-parse HEAD)
clean=true; [ -z "$(git -C "$SRC" status --porcelain -- "$REL")" ] || clean=false
cp "$SRC/$REL" "$DST"
python3 - "$PIN" "$commit" "$clean" "$DST" "$REL" <<'PY'
import hashlib, json, sys, datetime
pin, commit, clean, dst, rel = sys.argv[1], sys.argv[2], sys.argv[3] == "true", sys.argv[4], sys.argv[5]
doc = {
  "_comment": [
    "PROVENANCE PIN for md/testdata/liana_cases.json (F-449 stage 3, SPEC §8.1 Go leg).",
    "Generated by scripts/vendor-liana-cases.sh; never edited by hand.",
    "md/liana_test.go fails if the file's sha256 disagrees or the case count is not the one it asserts.",
  ],
  "repo": "descriptor-mnemonic",
  "remote": "git@github.com:bg002h/descriptor-mnemonic.git",
  "commit": commit,
  "repo_clean_when_recorded": clean,
  "path": rel,
  "sha256": hashlib.sha256(open(dst, "rb").read()).hexdigest(),
  "recorded_at": datetime.date.today().isoformat(),
}
json.dump(doc, open(pin, "w"), indent=2); open(pin, "a").write("\n")
print("vendored %s, primary %s" % (rel, commit[:12]))
PY
