#!/usr/bin/env bash
# Vendor the Rust primary's compose corpus (the MANIFEST's compose_* and
# keyed_compose_* vectors) into md/testdata/vectors/ and write the provenance
# pin md/compose_vectors_pin_test.go checks. Re-run on every re-pin.
#
#   scripts/vendor-compose-vectors.sh [/path/to/descriptor-mnemonic]
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${1:-$HERE/../descriptor-mnemonic}"
VEC="$SRC/crates/md-codec/tests/vectors"
DST="$HERE/md/testdata/vectors"
PIN="$HERE/md/testdata/compose_vectors.provenance.json"
[ -d "$VEC" ] || { echo "no vectors at $VEC" >&2; exit 2; }
commit=$(git -C "$SRC" rev-parse HEAD)
clean=true; [ -z "$(git -C "$SRC" status --porcelain -- crates/md-codec/tests/vectors)" ] || clean=false
mapfile -t files < <(cd "$VEC" && ls | grep -E '^(keyed_)?compose_' | sort)
[ "${#files[@]}" -gt 0 ] || { echo "no compose_* vectors in $VEC" >&2; exit 2; }
for f in "${files[@]}"; do cp "$VEC/$f" "$DST/$f"; done
python3 - "$PIN" "$commit" "$clean" "$DST" "${files[@]}" <<'PY'
import hashlib, json, sys, os, datetime
pin, commit, clean, dst, files = sys.argv[1], sys.argv[2], sys.argv[3] == "true", sys.argv[4], sys.argv[5:]
rows = [{"name": f, "sha256": hashlib.sha256(open(os.path.join(dst, f), "rb").read()).hexdigest()} for f in files]
names = sorted({f.split(".", 1)[0] for f in files})
doc = {
  "_comment": [
    "PROVENANCE PIN for the vendored compose corpus (wallet-policy composer, Stage 2).",
    "Generated by scripts/vendor-compose-vectors.sh; never edited by hand.",
    "md/compose_vectors_pin_test.go fails if any pinned file's sha256 disagrees,",
    "if the file count is not 156, or if the vector names drift from its list.",
    "TO RE-PIN: scripts/vendor-compose-vectors.sh /path/to/descriptor-mnemonic",
  ],
  "repo": "descriptor-mnemonic",
  "remote": "git@github.com:bg002h/descriptor-mnemonic.git",
  "commit": commit,
  "repo_clean_when_recorded": clean,
  "path": "crates/md-codec/tests/vectors",
  "files": rows,
  "vectors": len(names),
  "recorded_at": datetime.date.today().isoformat(),
}
json.dump(doc, open(pin, "w"), indent=2); open(pin, "a").write("\n")
print("vendored %d files, %d vectors, primary %s" % (len(rows), len(names), commit[:12]))
PY
