package seal

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"testing"
)

// The canonical MNEMBLOB vectors (SPEC §11.4 A–G), generated by the normative
// Rust implementation and copied verbatim into testdata/. See
// testdata/README.md: this file is data, never hand-edited, and a disagreement
// between it and this package is a Go bug.
//
// Everything in this package's suite reads its expectations from these fields
// rather than from retyped constants — retyped constants are how a port
// silently forks.

type vector struct {
	Name            string   `json:"name"`
	Passphrase      *string  `json:"passphrase"`
	Iterations      uint32   `json:"iterations"`
	SaltHex         string   `json:"salt_hex"`
	IVHex           string   `json:"iv_hex"`
	Public          []string `json:"public"`
	Secret          []string `json:"secret"`
	PubLen          uint32   `json:"pub_len"`
	CtLen           uint32   `json:"ct_len"`
	BlobHex         string   `json:"blob_hex"`
	BlobSHA256      string   `json:"blob_sha256"`
	HeaderHex       string   `json:"header_hex"`
	DerivedKeyHex   *string  `json:"derived_key_hex"`
	TagHex          *string  `json:"tag_hex"`
	PubhashSealed   *string  `json:"pubhash_sealed"`
	PubhashUnsealed *string  `json:"pubhash_unsealed"`
}

// Blob returns the vector's raw bytes.
func (v vector) Blob(t *testing.T) []byte {
	t.Helper()
	return mustHex(t, v.BlobHex)
}

type vectorFile struct {
	Note    string   `json:"note"`
	Spec    string   `json:"spec"`
	Vectors []vector `json:"vectors"`
}

// wantVectorNames pins the shape of the file itself. A truncated or reordered
// testdata file would otherwise silently shrink the suite: a `for range
// vectors` loop over three vectors passes just as green as one over seven.
var wantVectorNames = []string{"A", "B", "C", "D", "E", "F", "G"}

func loadVectors(t *testing.T) []vector {
	t.Helper()
	raw, err := os.ReadFile("testdata/vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var f vectorFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(f.Vectors) != len(wantVectorNames) {
		t.Fatalf("vectors.json has %d vectors, want %d", len(f.Vectors), len(wantVectorNames))
	}
	for i, want := range wantVectorNames {
		if f.Vectors[i].Name != want {
			t.Fatalf("vector %d is %q, want %q", i, f.Vectors[i].Name, want)
		}
	}
	// Self-consistency: blob_sha256 is a hash OF blob_hex, so a hand-edit of
	// either alone is caught here rather than as a confusing failure later.
	for _, v := range f.Vectors {
		sum := sha256.Sum256(mustHex(t, v.BlobHex))
		if got := hex.EncodeToString(sum[:]); got != v.BlobSHA256 {
			t.Fatalf("vector %s: blob_hex hashes to %s, but blob_sha256 says %s",
				v.Name, got, v.BlobSHA256)
		}
	}
	return f.Vectors
}

func vectorNamed(t *testing.T, name string) vector {
	t.Helper()
	for _, v := range loadVectors(t) {
		if v.Name == name {
			return v
		}
	}
	t.Fatalf("no vector %q", name)
	panic("unreachable")
}

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

// TestVectorsAreLoadable is the canary for the whole suite. Every other test
// reads its expectations from this file; if it stops loading, the rest of the
// package would still be "green" while asserting nothing.
func TestVectorsAreLoadable(t *testing.T) {
	vs := loadVectors(t)
	var summary string
	for _, v := range vs {
		summary += fmt.Sprintf("%s(pub=%d ct=%d) ", v.Name, v.PubLen, v.CtLen)
	}
	t.Logf("loaded %d vectors: %s", len(vs), summary)
}

// bs converts a fixture's []string to the [][]byte the pipeline now takes.
// AdmittedRecord.Record is []byte so Payload.Wipe can zero it; a Go string
// cannot be zeroed (§10.2 step 10).
func bs(ss []string) [][]byte {
	out := make([][]byte, len(ss))
	for i, s := range ss {
		out[i] = []byte(s)
	}
	return out
}
