//go:build js

// The SECOND systemwide test payload: the one carrying cosigner KEY CARDS.
//
// Confined by TestEveryEmbeddedPayloadIsStructurallyConfined, which discovers
// this file's `//go:embed` rather than matching a name — which is why this blob
// could be added without editing a guard, and why the next one can be too.
//
// WHY IT EXISTS. sysw_test_payload.bin holds ClassMnemonic, ClassPassphrase and
// ClassFreeText and ZERO ClassMDMK. Build policy's cosigner gather therefore has
// nothing to gather in the emulator, so an automated walk halts one screen
// BEFORE the dead-end (F-150 item 1) the plan exists to fix. Found by the
// journeys lens after five review rounds had accepted "emulator walk" as a gate.
//
// WHY NOT EXTEND THE FIRST BLOB. Its digest is pinned at
// sysw_test_payload.go's `syswTestDigest` and photographed in the published
// document design/journeys/SeedHammer-II-load-payload-journey.pdf. Editing it
// makes that document wrong in the one way a reader cannot detect — it would
// still read as consistent.
//
// RECORD INVENTORY — stated here because not stating it is exactly how the
// first blob's gap survived. Ten records, in this order:
//
//	@0..@1   mk1  master A, m/48'/0'/0'/2'   (2 chunks)
//	@2..@4   mk1  master A, m/48'/0'/1'/2'   (3 chunks)
//	@5..@6   mk1  master B, m/48'/0'/0'/2'   (2 chunks)
//	@7..@8   mk1  master C, m/48'/0'/0'/2'   (2 chunks)
//	@9       ClassMnemonic — master A
//
// WHICH STAGE NEEDS WHAT. Deleting any line strands that stage's walk:
//
//	S1, S2   two cosigner cards (B@0, C@0) for Trace A's 2-of-3
//	S3       the same cards; the sh(wsh) wrapper is a TEMPLATE-PICKER choice,
//	         not a payload property, so no extra record is needed — recorded
//	         because the plan briefly implied otherwise
//	S4       the HONEST `both` case: card A@0's key genuinely derives from the
//	         ClassMnemonic record at that card's declared origin, so the gate
//	         can be walked green. The FAILING case needs no extra record —
//	         assign B@0 or C@0 to a `both` slot against master A and the gate
//	         must refuse
//	S5       Trace B: A@0 and A@1 (one master, two accounts) plus B@0 (second
//	         master) and C@0 — multi-slot, divergent origins, multi-master
//
// PROVENANCE. Generated by `go run ./cmd/buildpayloadcards | me sysw pack
// --no-passphrase --in - --out cmd/emu/sysw_cards_payload.bin`, through the
// device's own derivation path (bip39.MnemonicSeed → hdkeychain.NewMaster →
// bip32.Derive → Neuter). Regenerate with that command; do not hand-edit.
//
// TEST MATERIAL, public by construction: masters A, B and C are BIP-39's own
// published vectors (`abandon…about`, `legal winner…yellow`,
// `letter advice…above`). The payload is UNSEALED, so there is no secret here
// to leak. Never put funds behind them.
package main

import (
	_ "embed"

	"seedhammer.com/sysw"
)

//go:embed sysw_cards_payload.bin
var syswCardsPayload string

// syswCardsDigest is what `me sysw show` prints for that blob, and therefore
// what the device shows an operator comparing it. Pinned by
// TestSyswCardsPayloadMatchesItsDigest so the two cannot drift.
const syswCardsDigest = "2527 1e58 3f3e aa03 ae18 f359 c72b 76e3"

// syswCardsReader serves the cosigner-card payload. Same shape as
// embeddedSyswReader; a separate type because a walk chooses BETWEEN them, and
// a single reader with a mutable blob would let one walk's choice leak into the
// next.
type syswCardsReader struct{ data []byte }

var _ sysw.Reader = syswCardsReader{}

func (r syswCardsReader) Probe() bool {
	return len(r.data) >= len(sysw.MAGIC) && [8]byte(r.data[:8]) == sysw.MAGIC
}

func (r syswCardsReader) Read() ([]byte, error) {
	if !r.Probe() {
		return nil, sysw.ErrBadMagic
	}
	out := make([]byte, len(r.data))
	copy(out, r.data)
	return out, nil
}
