//go:build js

// The THIRD systemwide test payload: the one carrying the Wallet Policy
// COMPOSER's own record classes.
//
// Confined by TestEveryEmbeddedPayloadIsStructurallyConfined, which discovers
// this file's `//go:embed` rather than matching a name — which is why the
// second blob could be added without editing a guard, and why this third one
// could too.
//
// WHY IT EXISTS. sysw_test_payload.bin holds ClassMnemonic, ClassPassphrase and
// ClassFreeText; sysw_cards_payload.bin holds mk1 cosigner cards and a
// ClassMnemonic. NEITHER holds a ClassKey, a ClassHash or a ClassNow, so in the
// emulator the composer's key sources are empty, its hash-lock picker has
// nothing to offer but `Type 64 hex`, and a time lock has no pack-time bound to
// echo. Spec §12 item 2 makes the C8 journey an emulator walk over exactly
// those screens, and before this blob no walk could reach them.
//
// WHY NOT EXTEND EITHER EXISTING BLOB. Their digests are pinned beside their
// own embeds AND photographed — the records blob in the published Load Payload
// journey, the cards blob in the cosigner-card walks. Editing one makes a
// published document wrong in the one way a reader cannot detect: it would
// still read as consistent.
//
// RECORD INVENTORY — stated here because not stating it is exactly how the
// FIRST blob's gap (three records, zero ClassMDMK) survived five review rounds.
// Five records, in this order:
//
//	@0   key:  master A, [73c5da0a/48'/0'/0'/2']xpub6DkFA…KFrf   (ClassKey)
//	@1   key:  master A, [73c5da0a/48'/0'/1'/2']xpub6Dzhy…d6Vk   (ClassKey)
//	@2   hash: abababab…abababab                                 (ClassHash)
//	@3   now:  1788220800,905000                                 (ClassNow)
//	@4   ClassMnemonic — master B
//
// WHAT EACH RECORD IS FOR. Deleting any line strands the screen beside it:
//
//	@0, @1  the composer's key SOURCES: the seating picker's two rows, and the
//	        2-of-2 path they fill. They are ONE MASTER AT TWO ACCOUNTS on
//	        purpose — that is what fires §8g's same-seed warning at the mapping
//	        review ("Slots @0 and @1 are the same seed…"), a screen no other
//	        emulator fixture reaches. Read as a defect it is a false alarm; it
//	        is the fixture's purpose.
//	@2      the hash-lock picker's `hash 1  abababab..abababab` row, and with
//	        it the §8i preimage modal, which is drawn on the way through.
//	@3      the pack time. Present so the composer HAS a bound; the fixture's
//	        lock is RELATIVE (12960 blocks), whose echo carries no bound line,
//	        so this record is what an ABSOLUTE lock's echo would draw from.
//	@4      the seed slot @2 is seated from, through `Type a seed` → `FROM
//	        PAYLOAD`. A SECOND master, so the keyed policy spans two, and the
//	        device seats it at ITS OWN account 0' rather than at md's
//	        lowest-free 2' — the divergence the keyed arm's oracle is minted
//	        against.
//
// PROVENANCE. Generated by `go run ./cmd/buildpayloadcomposer | me sysw pack
// --no-passphrase --out <this file's .bin>`, through the device's own
// derivation path (bip39.MnemonicSeed → hdkeychain.NewMaster → bip32.Derive →
// Neuter), and the generator REFUSES to emit if that path disagrees with the
// `ms`-derived xpubs pinned in it. `me sysw pack` reads records from STDIN when
// given neither --in nor argv; `--in -` is NOT a stdin spelling. Regenerate
// with that command; do not hand-edit.
//
// TEST MATERIAL, public by construction: masters A and B are BIP-39's own
// published vectors (`abandon…about`, `legal winner…yellow`) and the hashlock
// digest is a repeating byte, not the hash of anything anybody holds. The
// payload is UNSEALED, so a passphrase protects nothing here — there is
// nothing here to protect. Never put funds behind them.
package main

import (
	_ "embed"

	"seedhammer.com/sysw"
)

//go:embed sysw_composer_payload.bin
var syswComposerPayload string

// syswComposerDigest is what `me sysw show` prints for that blob, and therefore
// what the device shows an operator comparing it across the air gap. Pinned by
// TestSyswComposerPayloadMatchesItsDigest so the two cannot drift.
const syswComposerDigest = "dbe9 e774 e9a4 9231 0b62 626c 2b41 cf4b"

// syswComposerReader serves the composer payload. Same shape as
// syswCardsReader; a separate type for the same reason it was a separate type
// there — a walk chooses BETWEEN the blobs, and a single reader with a mutable
// blob would let one walk's choice leak into the next.
type syswComposerReader struct{ data []byte }

var _ sysw.Reader = syswComposerReader{}

func (r syswComposerReader) Probe() bool {
	return len(r.data) >= len(sysw.MAGIC) && [8]byte(r.data[:8]) == sysw.MAGIC
}

func (r syswComposerReader) Read() ([]byte, error) {
	if !r.Probe() {
		return nil, sysw.ErrBadMagic
	}
	out := make([]byte, len(r.data))
	copy(out, r.data)
	return out, nil
}
